### ISSUE TITLE
Movement values onDrag with scroll

### ISSUE THREAD

**Issue by emcfarlane** [pmndrs/use-gesture#338]
**Describe the bug**

On the desktop where scroll isn't disabled dragging an item out of bounds causes the movement value to be incorrect and drift from the mouse.

**Sandbox or Video**
https://codesandbox.io/s/romantic-satoshi-z8ugn?file=/src/App.tsx

https://user-images.githubusercontent.com/3036610/126230258-1c9cfaa8-e8d9-44e8-b8f7-7f1edac05da1.mov

**Information:**
 - '@use-gesture/react'
 - Device: Desktop
 - OS: macOS BigSur
 - Browser: Safari

**Checklist:**
  - [x] I've read the [documentation](https://use-gesture.netlify.app/).
  - [x] If this is an issue with drag, I've tried setting `touch-action: none` to the draggable element.

I don't think this is a bug, I've looked through the docs and issues to try find a solution but I'm not able to understand what the problem is. I'd like to eventually control the scroll and move the draggable item up and down the page. Is it easy to fix? Could I get some pointers on what a solution would look like? Thanks!

**Comment by dbismut** [comment]
The problem that you have is that selecting the text from the dragged item also triggers the browser scrolling. You should probably add `user-select: none` to your CSS to disable selecting the text on your dragged element.

This isn't a simple problem by any means AFAIK, the logic would be to add scrolling logic when your dragged element comes near the edges of the scrollable parent. If your element has absolute positioning, you'll probably have to compensate the scroll offset to keep your element under your mouse. Another tactic would be to use fixed positioning when the element is being dragged so that its positioning is independent from the scroll offset, but then you would have to recalculate the rest position when you remove the fixed positioning and perform a nice transition.

On this sort of complex usecases, I would look at using dedicated libs such as https://github.com/atlassian/react-beautiful-dnd or at least looking at how they do it internally.

Another way would be to try using framer-motion which has FLIP transitioning built-in, but you'd still have to handle the scroll logic on your end.

**Comment by emcfarlane** [comment]
Thanks for the detailed response. Please feel free to close the issue. I'll update when I have a shareable demo.

**Comment by emcfarlane** [comment]
I found some code you posted on a different issue for controlling the window scroll with react spring 😄. Modified it to use the api values to update the position and calculate the difference in height. It's a bit janky I think because of how I'm updating the `scrollDiff` var. Do you know how to make it smoother?

https://codesandbox.io/s/romantic-satoshi-z8ugn?file=/src/App.tsx

https://user-images.githubusercontent.com/3036610/126379479-7411e280-83e7-4e68-8494-baf33c238033.mov

**Comment by alekseyBatuhtin** [comment]
I have the same issue with dragging and scrolling, but the solution with `scrollDiff` has the problem.

https://codesandbox.io/s/compassionate-rain-36ddxh

https://user-images.githubusercontent.com/20453923/156874637-f80d17ae-2bf7-4acb-90d6-0fbb2ed7b29d.mp4


It looks like we should add `scrollDiff` into movement value when calling next `onDrag` handler. But using `memo` is a weird path, I think so.
Have lib tricks for changing `movement, distance` at the next call nicer?
