### ISSUE TITLE
drag event fires earlier than pointerdown event

### ISSUE THREAD

**Issue by smashercosmo** [pmndrs/use-gesture#365]
**Describe the bug**
When both onDrag and onPointerDown handlers are specified, onDrag executes earlier than onPointerDown. Maybe it's by design, but looks very counterintuitive to me.

**Sandbox or Video**
If it's not something obvious, I can provide sandbox, that demonstrates the issue 

**Information:**
 - React Use Gesture version: 10.0.2

**Checklist:**
  - [X] I've read the [documentation](https://use-gesture.netlify.app/)

**Comment by dbismut** [comment]
I don’t see the use case I’m sorry. Drag starts when the `pointerdown` event is fired. The fact that your own `pointerdown` logic comes after or before the drag handler being fired is an implementation detail. 

 Please provide a sandbox demonstrating the problem and I’ll reopen.

**Comment by smashercosmo** [comment]
Well, as I said it's a bit counterintuitive. I mean, how can you even start dragging something if you haven't pressed mouse button first?
Here is codesandbox that demonstrates the issue https://codesandbox.io/s/loving-danilo-3yd8t?
Currently if you need to perform some logic before drag you have to do something like this
```js
useGesture(
    {
      onDrag({ first }) {
        if (first) { ... do something before drag ... }
      },
    },
  )
```

This check is being performed every time event is being fired. Seems like more logical behaviour would be to execute onPointerDown handler first. And every logic that should be performed before drag would go into that handler.

**Comment by dbismut** [comment]
The `onPointerDown` handler is also used by the drag gesture. Yes, the lib could chain logic belonging to "native" handlers **before** the gesture handlers, but then you would argue that `onPointerEnd` should be fired **after** the drag is released.

Plus, the drag gesture has a lot of options, adapts its handlers depending on the device capabilities, meaning using `onPointerDown` to add to the drag logic is a bad practice. 

If you're reluctant to use the `first` attribute because of performance issue, there's really no need to worry. 

If this is for aesthetics reasons, you can use `onDragStart` which is available in `useGesture`.

**Comment by smashercosmo** [comment]
Alright, thx for the explanation and the tip)
