### ISSUE TITLE
xy isn't affected by transform in 10.0.0+

### ISSUE THREAD

**Issue by mordv** [pmndrs/use-gesture#402]
Hi! I was relying on `xy` to be transformed by the transform function. After an update, I've noticed it's not the case anymore: [Codesandbox](https://codesandbox.io/s/transform-xy-9t8q4?file=/src/Box.js:829-832). Is that intentional?

**Comment by dbismut** [comment]
Hi @mordv thanks for this. This was a rather heavy fix tbh since I realized the way I applied the transform function wouldn't perform correctly if the function doesn't have a `[0,0]` origin. Therefore I had to adjust some internals, hence the version bump to `10.2.0` which also transforms `xy`.

Let me know how it goes.
