### ISSUE TITLE
React: useDrag in child components gets interrupted, when list is reordered

### ISSUE THREAD

**Issue by Tauka** [pmndrs/use-gesture#608]
**Describe the bug**
In React, when reordering list by dragging items, if component rerendered with reordered list, `useDrag` in children gets interrupted.

**Sandbox or Video**
https://codesandbox.io/s/loving-williamson-h6lchj?file=/src/App.js

Try to drag any item to the right, items get swapped, but drag gets interrupted
**Information:**
 - Use Gesture version: v10.2.25
 - Device: Macbook Pro 16
 - OS: macOS 13.0.1
 - Browser: Chrome 114.0.5735.106

**Checklist:**
  - [x] I've read the [documentation](https://use-gesture.netlify.app/).
  - [x] If this is an issue with drag, I've tried setting `touch-action: none` to the draggable element.

**Comment by dbismut** [comment]
Hi @Tauka, and I'm also tagging @volkov85 and @Aegario who upvoted this so that they can be notified.

I've refactored the original list example of this repo into a much more circumvoluted one that you'll find here:
https://codesandbox.io/s/adoring-neco-ff4nnw?file=/src/App.jsx

Contrary to the original one which triggers zero re-render, this one triggers both a re-render on the parent component every time the list is re-ordered, and a re-render on the dragged child every time its drag status changes.

As you can see it works perfectly fine.

I'm not sure what's wrong with your example (I was honestly too lazy to dig), but it doesn't feel right (the use of refs, useEffect, indexes is really weird).

What I can see from the logs from the library is that the reason why the drag is interrupted is because a PointerUp event is fired, which has nothing to do with the component being re-rendered.

<img width="313" alt="image" src="https://github.com/pmndrs/use-gesture/assets/5003380/791fdc31-8ab3-4695-ad9e-f52d83d09c71">
